apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce
  # storage class ini adalah sebuah konsep bawaan kubernetes untuk inisialisasi bagaimana cara penyajian data, untuk kasus kali ini cukup pake yang bawaan aja, yaitu standart
  storageClassName: standart # cek di : kubectl get sc
  resources:
    requests:
      # ini akan klaim size storage di persistance volume, pastikan tidak lebih besar dari kapasitasnya (cek host-pv.yaml), disini kalo ada beberapa klaim, pastikan pembagiannya rata
      storage: 1Gi
# cek : kubectl get pvc
