kind: Service
apiVersion: v1
metadata:
  name: story-service
spec:
  selector:
    app: story-app
  type: LoadBalancer
  ports:
    - name: story-port
      port: 80
      targetPort: 3000
# KETIKA MEMBUAT SEBUAH DEPLOYMENT DENGAN REPLICAS LEBIH DARI 1, KUBERNETES AKAN MEMDUPLIKASI POD YA, BUKAN CONTAINERNYA. SEDANGKAN DALAM SEBUAH POD ITU BISA ADA LEBIH DARI 1 CONTAINER

# TYPE SERVICE DENGAN SPEK LOAD BALANCER INI AKAN MENORMALISASI SEBUAH IP YANG DITUJUKAN UNTUK POD2 TERSEBUT WALAUPUN LEBIH DARI 1 POD AKAN DI NORMALISASI DENGAN IP YANG SAMA. NAH, DENGAN BEGITU REPLICAS INI BISA JADI SCALING OPTION
